### ISSUE TITLE
Fails on zip archives with paths 

### ISSUE THREAD

**Issue by stmyers** [jorritfolmer/TA-dmarc#2]
I'm backfilling with reports from a while ago, and it's been choking on this one:
```
$ unzip -l etat.lu\!domain.com\!1449067864\!1449212471.zip
Archive:  etat.lu!domain.com!1449067864!1449212471.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     3884  12-04-2015 08:01   /var/log/opendmarc/temp/etat.lu!domain.com!1449067864!1449212471.xml
```

Here's the error from TA-dmarc:
```
2017-11-20 10:16:35,006 ERROR pid=6663 tid=MainThread file=base_modinput.py:log_error:307 | Get error when collecting events.
Traceback (most recent call last):
  File "/disk2/opt/splunk/etc/apps/TA-dmarc/bin/ta_dmarc/modinput_wrapper/base_modinput.py", line 127, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/TA-dmarc/bin/dmarc_directory.py", line 72, in collect_events
    input_module.collect_events(self, ew)
  File "/disk2/opt/splunk/etc/apps/TA-dmarc/bin/input_module_dmarc_directory.py", line 47, in collect_events
    d2s.process_incoming()
  File "/disk2/opt/splunk/etc/apps/TA-dmarc/bin/dmarc/dir2splunk.py", line 290, in process_incoming
    lines = self.process_xmlfile_to_lines(xmlfile,0)
  File "/disk2/opt/splunk/etc/apps/TA-dmarc/bin/dmarc/dir2splunk.py", line 241, in process_xmlfile_to_lines
    with open(file, 'r') as f:
IOError: [Errno 2] No such file or directory: '/var/log/opendmarc/temp/etat.lu!domain.com!1449067864!1449212471.xml'
```

I'm guessing this is an issue with an incorrectly formatted DMARC report archive, but it might be worth accounting for this.

**Comment by jorritfolmer** [comment]
Thanks for posting this!
I'll take a look.
Can you share that zip? I'll try recreating a zip with a path, but yours is special because it has an absolute path. I'm unable to create a zip with an absolute path on the cmdline.

**Comment by stmyers** [comment]
Hi sorry, I cannot share as it has some company info (I know it's not sensitive necessarily but I'd have to vet through legal before sharing...not worth the effort).

**Comment by jorritfolmer** [comment]
This is still on my TODO, don't worry.
Quite busy atm though. I'll update when time permits.

**Comment by jorritfolmer** [comment]
I found that `7za` has a flag to preserve the entire path of files:

`7za -spf a test.zip /file/with/absolute/path/preserved`

**Comment by jorritfolmer** [comment]
Ok fixed with most recent commit.
Thanks again for submitting this issue!
